import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/NavbarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Geo Notes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-h-screen h-screen flex flex-col">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
